spring.application.name=FretesDrones
spring.config.import=optional:file:./.env[.properties]
server.port=8080
debug=false
logging.level.org.springframework=INFO
spring.mongodb.uri=${MONGODB_URI}

# JWT
jwt.secret=${JWT_SECRET:8f83c16265780fa34fbe161b4fa1f97486e08c3e800c43c229341ba228b3a060}
jwt.expiration=7200000
